// <auto-generated />
using System;
using CabsBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CabsBooking.Infrastructure.Migrations
{
    [DbContext(typeof(CabsBookingDbContext))]
    [Migration("20201218185918_ModifyNullableAndRelationship")]
    partial class ModifyNullableAndRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("CabTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FromPlace")
                        .HasColumnType("int");

                    b.Property<string>("Landmark")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("date");

                    b.Property<string>("PickupTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ToPlace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabTypeId");

                    b.HasIndex("FromPlace");

                    b.HasIndex("ToPlace");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.BookingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("CabTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("FromPlace")
                        .HasColumnType("int");

                    b.Property<string>("Landmark")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("date");

                    b.Property<string>("PickupTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ToPlace")
                        .HasColumnType("int");

                    b.Property<decimal?>("charge")
                        .HasColumnType("money");

                    b.Property<string>("comp_time")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("CabTypeId");

                    b.HasIndex("FromPlace");

                    b.HasIndex("ToPlace");

                    b.ToTable("Bookings_history");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.CabType", b =>
                {
                    b.Property<int>("CabTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CabTypeName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CabTypeId");

                    b.ToTable("CabTypes");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PlaceName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.Booking", b =>
                {
                    b.HasOne("KaiHungHuang.CabsBooking.Core.Entity.CabType", "CabType")
                        .WithMany("Bookings")
                        .HasForeignKey("CabTypeId");

                    b.HasOne("KaiHungHuang.CabsBooking.Core.Entity.Place", "FromPlaceName")
                        .WithMany("FromPlaceBookings")
                        .HasForeignKey("FromPlace");

                    b.HasOne("KaiHungHuang.CabsBooking.Core.Entity.Place", "ToPlaceName")
                        .WithMany("ToPlaceBookings")
                        .HasForeignKey("ToPlace");

                    b.Navigation("CabType");

                    b.Navigation("FromPlaceName");

                    b.Navigation("ToPlaceName");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.BookingHistory", b =>
                {
                    b.HasOne("KaiHungHuang.CabsBooking.Core.Entity.CabType", "CabType")
                        .WithMany("BookingHistories")
                        .HasForeignKey("CabTypeId");

                    b.HasOne("KaiHungHuang.CabsBooking.Core.Entity.Place", "FromPlaceName")
                        .WithMany("FromPlaceBookingHistories")
                        .HasForeignKey("FromPlace");

                    b.HasOne("KaiHungHuang.CabsBooking.Core.Entity.Place", "ToPlaceName")
                        .WithMany("ToPlaceBookingHistories")
                        .HasForeignKey("ToPlace");

                    b.Navigation("CabType");

                    b.Navigation("FromPlaceName");

                    b.Navigation("ToPlaceName");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.CabType", b =>
                {
                    b.Navigation("BookingHistories");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KaiHungHuang.CabsBooking.Core.Entity.Place", b =>
                {
                    b.Navigation("FromPlaceBookingHistories");

                    b.Navigation("FromPlaceBookings");

                    b.Navigation("ToPlaceBookingHistories");

                    b.Navigation("ToPlaceBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
